version: "3.8"

services:
  redis-server:
    image: "redis"

  backend-redis:
    build:
      dockerfile: Dockerfile
      context: ./backend-redis
    container_name: app_backend_redis
    ports:
      - "9000:8080"
